name: Build Geode Mod
on: [push, pull_request]

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          bindings: 'geode-sdk/geode'
